### ISSUE TITLE
The plugin removes comments inside import() statements, e.g. /* webpackChunkName */

### ISSUE THREAD

**Issue by dko-slapdash** [LeDDGroup/typescript-transform-paths#58] opened 2020-05-05 00:21 UTC
```
# src/page.ts
import(/* webpackChunkName: "Some" */ "../pages/Some")
```

Without typescript-transform-paths, this correctly transpiles to the exactly same JS code, the comments remained.

With typescript-transform-paths, it transpiles to:

```
# dist/page.js
import("../pages/Some")
```

I.e. the plugin removes comments even when removeComments=false in tsconfig.json's compilerOptions.

This issue doesn't allow to use custom chunk names when e.g. using webpack to bundle the content of dist/ folder (which webpack does way way faster than ts-loader, especially in monorepo- composite- projects).

**Comment by nonara** [comment] 2020-07-29 19:14
I'm not certain that this can be avoided. At least not via the compiler API. Unfortunately, the TS Compiler API does not allow inserting or updating comments.

Unless I'm wrong, this would be a limitation on the TS compiler side and not a bug with this library.

**Comment by dko-slapdash** [comment] 2020-07-29 19:23
Is there a chance to to a text-based post-processing step once the compilation of a file finishes? Then it would be possible to dirty-replace at least no-op transformations with just regexps, like
```
const orig = 'import(/* webpackChunkName: "Some" */ "../pages/Some")';
const compiled = import("../pages/Some");
if (orig.replace(/\/\*.*?\*\/|\s/g, '') === compiled.replace(/\s/g, '')) {
  text = text.replace(orig, compiled);
}
```

**Comment by nonara** [comment] 2020-07-29 20:44
It can be done and integrated into the build process if you use a `programTransformer` with [ts-patch](https://npmjs.com). I wrote it to handle situations like that, but it requires a pretty strong knowledge of the TS compiler API and working with AST nodes. Steep curve if you're new to that.

Regex replace is going to have some problems, especially if it has quotes. AST is probably going to be best.

Here are the steps, if you're interested in pursuing it:

1. Create a map for tracking nodes `Map<Node, { comment: string, position: number, length: number }>`
2. Make a Program Transformer entry point (recieves program: `Program`) (steps that follow are performed inside entry point)
3. Transform all local SourceFiles (program.getSourceFiles() filter by program.getRootFileNames() with `ts.visitEachNode`
    - Use the same transform logic as found in this repo, but add this logic:
      - Add any relevant Nodes (import, export, etc) that get modified to your map. 
        Note: Get the Node's argument which is a `StringLiteral` (we'll call it `stringLiteralNode`) and set your map's `position` property to `stringLiteralNode.getFullStart()` and  the `length` property to `node.getFullStart() - getStart()` (This is your comment's position and length in the raw source text)
3. Use `ts.createPrinter().printFile()` on all files to render to source text
4. Use `splice` to re-insert your comments at the correct positions in the source text
5. Create a new `Program` from the transformed source and return it

Tools to use:

[ts-patch](https://npmjs.com)
[TS AST Viewer](https://ts-ast-viewer.com/#code/JYWwDg9gTgLgFAegFQAIAWBTANliKkIoDkAhgEYDGRAlANxA)

There are more resources for help on the docs for ts-patch. Good luck!

**Comment by nonara** [comment] 2020-07-30 00:21
If you like, @danielpza, you can close this, as it's a TS compiler issue.

**Comment by danielpza** [comment] 2020-07-30 00:33
If removing the comments inside imports it's not the default typescript behavior and with this transformer it does, it seems like a bug even if it's not possible to fix it from our side.

I'll probably leave it up for a while in case someone wants to chime in, and I"ll reference it in the readme before closing it. Thanks for the insight

**Comment by nonara** [comment] 2020-09-18 04:17
I did a little more research, and it looks like this should be possible now. I'll have a look at it when I can!

If anyone is following this thread and is interested, leave a comment so I know what the demand is.

**Closed** 2020-10-23 00:06 UTC
Labels: bug

**Comment by nonara** [comment] 2020-10-23 00:11
This should be sorted with the latest version! v2.0.2

Let us know if you have any issues with it.
