### ISSUE TITLE
[Bug?] Index file import not being transformed correctly

### ISSUE THREAD

**Issue by SammyWhamy** [LeDDGroup/typescript-transform-paths#159] opened 2022-05-24 22:01 UTC
I have this settings in my tsconfig:
```json
"paths": {
  "@util": ["util/index.js"]
}
```
But when I `import { } from "@util";`
It emits this code: `import { } from "../util";`
If I instead rename the file to something else, e.g. `barrel`, it emits this:  `import { } from "../util/barrel";`

The problem is, node can resolve neither of these. And as I specify that `@util` should be rewritten to `util/index.js` I expect it to keep the `index.js` part, without this my import simply doesn't function.

I can't really tell if this is intended behavior or not, but I think emitting the full path (including `index.js`) should always be a safe option if it is specified as such in the `paths` option.

I know I could instead do `"@util/*": ["util/*"]`
And then `import { } from "@util/index.js";`
But it'd be even better if I can have it emit the `index.js` for me as well.

**Comment by nonara** [comment] 2022-08-10 01:18
Hi @SammyWhamy .

Thanks for the report! Sorry to hear you're facing issues with the library. This could simply be an issue with rootDir or something to that effect. Though it looks like it might have to do with a known issue in handling indexes. I have this mostly fixed in the new version, but I have to complete it.

If you can provide a reproduction, I will have a look!

**Comment by nonara** [comment] 2022-10-20 21:24
Closing for housekeeping. Feel free to reopen if you have a reproduction.

**Closed by nonara** 2022-10-20 21:24 UTC
Labels: Needs Reproduction

**Comment by SammyWhamy** [comment] 2023-03-20 17:50
Came back to this after a while, with a reproduction!

I have the following typescript file:
```json
{
  "compilerOptions": {
    "lib": [
      "es2021",
    ],
    "module": "esnext",
    "target": "es2021",
    "moduleResolution": "Node",

    "sourceMap": true,
    "declaration": true,
    "strict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,

    "baseUrl": "./src",
    "rootDir": "./src",
    "outDir": "./dist",

    "plugins": [
      { "transform": "typescript-transform-paths" },
      { "transform": "typescript-transform-paths", "afterDeclarations": true}
    ],

    "paths": {
      "@client": ["client/index.js"],
      "@objects": ["objects/index.js"],
      "@cache": ["cache/index.js"],
      "@utils": ["utils/index.js"],
    }
  }
}
```
In my typescript files, I want to use imports in the following way:
```ts
import { Client, SomeOtherClass } from "@client";
```
Where `src/client/index.ts` is the following:
```ts
export * from './Client.js';
```
And `src/client/Client.ts` contains something like:
```ts
export class Client { }
export class SomeOtherClass { }
```

However, when building this source, the import does not get transformed, and stays as
```ts
import { Client, SomeOtherClass } from "@client";
```
Which obviously cannot be resolved by node, as now it's trying to look for a node module called `@client`
I'm using the current latest version of this package (`3.4.6`), and TypeScript `5.0.2`

**Comment by nonara** [comment] 2023-03-21 00:28
This is tied to a know issue with indexes #136. Hoping to have that sorted in the next major version.

For now, you can use the [@transform-path tag](https://github.com/LeDDGroup/typescript-transform-paths#transform-path-tag) to explicitly set the output  to `./client/index.js`
