### ISSUE TITLE
Not working for TypeScript 4.9?

### ISSUE THREAD

**Issue by stephenh** [LeDDGroup/typescript-transform-paths#168] opened 2022-11-17 18:13 UTC
I'm upgrading our codebase to 4.9.3 and noticing that paths are not being rewritten anymore.

I can put together a reproduction, but just wondering before I do that if this is a known issue/others have seen it/etc.

Thanks!

**Comment by carlocorradini** [comment] 2022-11-18 00:03
@stephenh Same issue

**Comment by nonara** [comment] 2022-11-18 00:34
Hi all. Unfortunately, this is an issue in 4.9. There was a regression with `visitEachChild`, which most transformers rely on. There is a fix ready and it's marked for renew. I had hoped it would make it in to 4.9.3, but it looks like it hasn't yet.

Here are the links so you can follow the issue & PRs

- https://github.com/microsoft/TypeScript/issues/51542
- https://github.com/microsoft/TypeScript/pull/51544
- https://github.com/microsoft/TypeScript/pull/51543

**Comment by bradennapier** [comment] 2022-12-02 15:15
The...wait...is...unbearable :-D good to know though, this should have been better communicated with the impact it had upon the ecosystem IMO.  Glad it is already in the works - no pre-builds of 4.9.4 yet :(

**Comment by DanielRosenwasser** [comment] 2022-12-08 00:04
4.9.4 is now out FWIW

**Comment by nonara** [comment] 2022-12-09 15:03
> typescript-transform-paths does not work on TS 4.9.4

`4.9.4` changes required changes to `ttypescript` and `ts-patch`. I investigated this and updated the methodology. The latest versions of tts and tsp now work with 4.9.4.

Having completed those updates, this library works. Simply make sure you're using the latest tts or tsp.

**Comment by carlocorradini** [comment] 2022-12-09 15:14
@nonara Awesome! Can we close this?

**Closed** 2022-12-09 15:45 UTC
Labels: Awaiting Upstream Fix
