### ISSUE TITLE
outDir is not taking into account

### ISSUE THREAD

**Issue by emmkimme** [LeDDGroup/typescript-transform-paths#103] opened 2021-05-10 18:15 UTC
Hi

likely my mistake, but I did not get it to work.

I have the following configuration (just keep relevant fields)
```
{
    "include": [
        "../../eikon-framework/src/**/*.ts"
    ],
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "df-core/*": ["./build/df-core/*"],
            "*": [
                "./node_modules/*",
                "./node_modules/@types/*"
            ]
        },
        "rootDir": "../../eikon-framework/src",
        "outDir": "./build/eikon-framework"
    }
}
```
I have the following file:
../../src/eikon-framework/src/auth/auth-impl.ts
`import { GetElectronEnvironment } from 'df-core/env';`

after the compilation in the outDir folder I have
[outDir]/eikon-framework/auth/auth-impl.js
`const env_1 = require("../../../products/workspace/build/df-core/env/index");`

It seems the resolution has been done from the original location of TS file and not from the output location of JS file.
With  "df-core/*": ["./build/df-core/*"] and outDir = ./build/eikon-framework/auth/auth-impl.js

I would expect
`const env_1 = require("../../df-core/env/index");`

Could you help me please

Thanks

**Comment by danielpza** [comment] 2021-05-11 00:35
Perhaps the [virtual directories](https://github.com/LeDDGroup/typescript-transform-paths#virtual-directories) would help in this case

**Comment by emmkimme** [comment] 2021-05-11 10:09
Looking at your implementation and debugging the plugin, I found a way to deal with rootDirs. 
```
{
    "include": [
        "../../eikon-framework/src/**/*.ts"
    ],
    "compilerOptions": {
        "rootDirs": ["./build/", "../../eikon-framework"],
        "baseUrl": ".",
        "paths": {
            "df-core/*": ["./build/df-core/*"],
            "*": [
                "./node_modules/*",
                "./node_modules/@types/*"
            ]
        },
        "rootDir": "../../eikon-framework/src",
        "outDir": "./build/eikon-framework"
    }
}
```
I'm wondering if we could have another way just using 'paths', 'rootDir' and 'outDir' to achieve the same. I have the feeling to duplicate the information.

Feel free to close this issue. and thanks for your help and this plugin.

**Comment by nonara** [comment] 2021-05-20 22:13
@emmkimme I'd like to have a look into this. Would you mind making a reproduction repo / branch for me to try it? I'm not entirely sure I see what's happening here, but it looks like an issue of tsconfig being in a totally separate location from the source files. You might be right that this shouldn't be the standard behaviour. I'd need an example to see what's going on, though.

**Comment by kainstar** [comment] 2021-05-31 08:24
I have same problem, I think the reason is transform plugin resolve relative path form source file rather than this output file, but sometimes we will emit files into the different level dir, that's why the final relative path is wrong.

I see this issue has tagged `Bug` label, is there has someone trying to solve it?

**Comment by couellet** [comment] 2021-06-08 21:30
I'm having a similar issue, here's my `tsconfig.json` file:

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "esnext",
        "moduleResolution": "node",
        "declaration": true,
        "outDir": "dist",
        "strict": true,
        "lib": ["es5", "ES2015.Promise", "DOM"],
        "stripInternal": true,
        "sourceMap": true,
        "strictNullChecks": true,
        "esModuleInterop": true,
        "noEmitHelpers": true,
        "importHelpers": true,
        "allowSyntheticDefaultImports": true,
        "allowJs": true,
        "experimentalDecorators": true,
        "rootDirs": ["./dist/", "../src"],
        "baseUrl": "./src",
        "rootDir": "src",
        "paths": {
            "@/*": [
                "./*"
            ]
        },
        "plugins": [{
            "transform": "typescript-transform-paths", "afterDeclarations": true, "useRootDirs": true
        }]
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

I just added `rootDirs` and `rootDir`, but it didn't change anything. I have the following file tree:

```
| - 📂src
| - 📂dist
| - 📃 tsconfig.json
```

So my compiled files are in the `dist` folder but it seems that the transformer doesn't run on these, paths remain absolute.

**Comment by danielpza** [comment] 2021-06-08 21:40
@couellet I think you need 2 entries in the plugin section for the transformer to actually work:

https://github.com/LeDDGroup/typescript-transform-paths#example-config

```
    "plugins": [
      { "transform": "typescript-transform-paths", "useRootDirs": true },
      { "transform": "typescript-transform-paths", "useRootDirs": true, "afterDeclarations": true }
    ]
```

**Comment by couellet** [comment] 2021-06-08 21:45
@danielpza that was it! Thank you so much.

**Comment by nonara** [comment] 2021-06-08 21:51
> I see this issue has tagged `Bug` label, is there has someone trying to solve it?

I will, but I need a reproduction

**Comment by nonara** [comment] 2021-06-16 20:56
Ok, all. I looked deeper into this and you were correct on it not resolving from `outDir`. Please give v3.0 a try and let me know if you have any issues. It should be sorted!

**Closed by nonara** 2021-06-16 20:56 UTC
Labels: Needs Reproduction

**Comment by kyle-belle** [comment] 2023-10-15 11:00
Hey there. @nonara was it ever confirmed fixed. I am using `"typescript-transform-paths": "^3.4.6"` and it still seems to have this behaviour. Makes it very hard to work in a monorepo or yarn workspaces

**Comment by kyle-belle** [comment] 2023-10-15 12:30
The `rootDirs` trick kind of works but now it causes `error TS5055: Cannot write file '/path/to/file.js' because it would overwrite input file.` after when i try to run tsc again since now my build folder is in `rootDirs`. i have to delete my build folder before running every time.

what would be nice is if this package had its own config where you could specify `rootDirs` without affecting tsc's `rootDirs` (And please if this is already possible kindly (or even rudely) let me know).

even an option like `backwardsRootDirsLookup` or something would be nice so i can put `"./build"` last in the `rootDirs` array
