### ISSUE TITLE
The plugin works only when "paths" exists in tsconfig, why?

### ISSUE THREAD

**Issue by dko-slapdash** [LeDDGroup/typescript-transform-paths#39] opened 2019-10-14 06:43 UTC
Thanks for this plugin!

I noticed that I have to add a dummy `"paths": { "*": ["*"] }` entry to tsconfig to make the transformer work. Without it, the module does nothing:

```
// tsconfig.json (no "paths" at all)
"baseUrl": "src"
"plugins": [{ "transform": "typescript-transform-paths" }],

// src/main.ts
import { app } from "electron";  // a module in node_modules
import { setMenu } from "main/menu";  // src/main/menu.ts; no syntax errors for tsc/vscode

// output:
const electron_1 = require("electron"); // correct
const menu_1 = require("main/menu"); // <-- INCORRECT, NOT ./main/menu
```

Adding a dummy entry `"paths": { "*": ["*"] }` solves the problem.

My IMHO is following: it's a little strange to require "paths" to be present in tsconfig.json. I think in an ideal world, the transform plugin should do exactly the same as TS does when it interprets the entire configuration. If TS understands just baseUrl and shows no syntax errors in both tsc and in VSCode, if it allows to do import from "xyz/abc" where xyz is located in baseUrl, then the transform plugin should do no worse than that. (And I also think that in an ideal world, tsc should have a config option to alter paths natively; although I read their arguments, they still look very weak to me.)

**Comment by danielpza** [comment] 2019-10-14 20:03
Yes, as you say `path` it's not always necessary, I was not aware of it. You are welcome to make a PR, otherwise I'll address it when I'm available.

ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#base-url

**Comment by danielpza** [comment] 2019-10-14 20:04
@all-contributors add @dko-slapdash for bug.

**Comment by danielpza** [comment] 2019-11-09 23:01
@dko-slapdash, the fix is up in v1.1.12, upgrade.

**Comment by dko-slapdash** [comment] 2020-11-22 01:58
@danielpza I think this regressed in v4, repro steps:

*package.json:*
```
{
  "name": "bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "esm": "^3.2.25",
    "ttypescript": "*",
    "typescript": "*",
    "typescript-transform-paths": "*"
  }
}
```

*tsconfig.json:*
```
{
  "compilerOptions": {
    "skipLibCheck": true,
    "jsx": "react",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "pretty": true,
    "resolveJsonModule": true,
    "target": "esnext",
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "strict": true,
    //"paths": { "*": ["*"] }, <-- UNCOMMENT THIS to make it work again
    "plugins": [
      { "transform": "typescript-transform-paths" },
    ],
    "rootDir": "src",
    "outDir": "dist",
    "baseUrl": "src"
  }
}
```

*src/a.ts:*
```
import { b } from "b";
console.log(b);
```

*src/b.ts:*
```
export const b = { b: 10 };
```

Run:
```
npm install && npx ttsc && cat dist/a.js
```

*Expected result in a.js:*
```
import { b } from "./b";
console.log(b);
```

*But got:*
```
import { b } from "b";
console.log(b);
```

**Comment by dko-slapdash** [comment] 2020-11-22 04:16
@nonara - this is where v2 works differently than v1.
Also, here is a related thing which I guess is different too: https://github.com/LeDDGroup/typescript-transform-paths/issues/42

**Comment by nonara** [comment] 2020-11-22 04:51
@dko-slapdash We made a determination with v2 to strictly adhere to the compiler's logic and to rely on the compiler API for module resolution. see: https://github.com/LeDDGroup/typescript-transform-paths/pull/66

The reason we released as a breaking change is because we knew that there could be some config which was divergent from TS's own module resolution methodology. 

Module resolution in v2 is now performed via `ts.resolveModuleName`. That in mind, if TS cannot resolve something without `paths` specified, then I wouldn't want to diverge from that, as the expected behaviour for v2+ is to match TS.

**Comment by dko-slapdash** [comment] 2020-11-22 07:29
Just to make sure we're talking about the same thing: TS itself _successfully resolves_ path like "b" to "src/b" thanks to its baseUrl (or rootDir? don't remember exactly). I.e. by itself, TS works fine without `"paths": { "*": ["*"] }` hack. If TS itself recognizes the path, then typescript-transform-paths should emit the correct path too, right? Because if typescript-transform-paths doesn't recognize some cases which TS does recognize, then it partially goes the same route as TS (with TS'es stubbornness to have any setting for path translation) goes.

**Comment by nonara** [comment] 2020-11-22 21:17
@dko-slapdash Sorry about that, I misunderstood. I actually didn't realize that you could map without paths. You're correct that `resolveModuleName` does resolve it. 

Related - TS 4.1 just made [baseUrl optional](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#paths-without-baseurl).

The code was originally written with an optimization such that if `baseUrl` and `paths` were not _both_ set, it would not run the transform logic. I've updated the logic to now require at least one of the two, which should cover your issue and the latest change.

I'm looking into the other issues now. You should see a release shortly

**Closed** 2020-11-23 02:41 UTC
Labels: Bug
